---
# defaults file for Vector-role
vector_version: 0.22.0
vector_dirs: "vector"
arch: x86_64
vector_config_dir: "/etc/vector"

vector_config:

  sources:
    demo_logs:
      type: demo_logs
      format: syslog
    in:
      type: stdin
  sinks:
    to_clickhouse:
      type: clickhouse
      inputs:
        - demo_logs
        - in
      database: logs
      endpoint: http://localhost:8123
      table: alerts
      compression: gzip
      healthcheck: true
      skip_unknown_fields: true 