---
# tasks file for Vector-role

- name: Download Vector distrib
  ansible.builtin.get_url:
    url: "https://packages.timber.io/vector/{{ vector_version }}/vector-{{ vector_version }}-1.{{ arch }}.rpm"
    dest: "./vector-{{ vector_version }}-1.{{ arch }}.rpm"
    #mode: "0644"

- name: Install Vector packages
  #become: true
  ansible.builtin.yum:
    name: vector-{{ vector_version }}-1.{{ arch }}.rpm
    disable_gpg_check: true

- name: Copy Vector config
  #become: true
  ansible.builtin.template:
    src: vector.yml.j2
    dest: "{{ vector_config_dir }}/vector.yml"
    mode: "0644"
    owner: "{{ ansible_user_id }}"
    group: "{{ ansible_user_gid }}"
    validate: vector validate --no-environment --config-yaml %s

- name: Vector change systemd unit
  become: true
  ansible.builtin.template:
    src: vector.service.j2
    dest: /usr/lib/systemd/system/vector.service
    mode: "0644"
    owner: "{{ ansible_user_id }}"
    group: "{{ ansible_user_gid }}"
    backup: true
  notify: Start Vector service